name: Update Baidu Hotsearch

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: true

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'  

    - name: Install requirements
      run: pip install -r requirements.txt

    - name: Run hotsearch script
      run: python get_baidu_hotsearch.py

    - name: Commit changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add baidu_hotsearch.json bing.js requirements.txt
        git commit -m "Update baidu hotsearch data [skip ci]" || echo "No changes to commit"
        git push https://x-access-token:$GITHUB_TOKEN@github.com/${{ github.repository }}.git
